---
title: "R Notebook"
output: html_notebook
---



```{r}
per_fv_2020=read_parquet("./data/financial year/plfs_per_fv_2020.parquet")
hh_fv_2020=read_parquet("./data/financial year/plfs_hh_v1_2019.parquet")
```

```{r}
per_fv_2020 = prepare_plfs_data("2020")
```


```{r}
per_fv_2020=per_fv_2020%>%
  mutate(nic_2digit_principal=substr(b5pt1q5_perv1,1,2),
         nic_3digit_principal=substr(b5pt1q5_perv1,1,3),
         nco_1digit_principal=substr(b5pt1q6_perv1,1,1))%>%
  type.convert(as.is=T)%>%
  mutate(dummy_area="All India",
          age_group=case_when(b4q6_perv1<15~"0-15",
                              b4q6_perv1>=15 & b4q6_perv1<30~"15-29",
                              b4q6_perv1>=30 & b4q6_perv1<50~"30-49",
                              b4q6_perv1>=50 & b4q6_perv1<60~"50-59",
                              b4q6_perv1>=60~"60 and Above"),
         labour_force=if_else(b5pt1q3_perv1<=81 | b5pt1q7_perv1==1,"Yes","No"),
         worker_yn=if_else(b5pt1q3_perv1<81 | b5pt1q7_perv1==1,"Yes","No"),
         weight_f =  if_else(NSS_perv1==NSC_perv1,mult_perv1/400,mult_perv1/800),
         working_age_yn=age_group %in% c("15-29","30-49","50-59"),"Yes","No")
```


```{r}
per_fv_2020=prepare_plfs_data("2020")
```


```{r}
per_fv_2020 %>%
  mutate(training_type = as.factor(
    case_when(
      b4q12_perv1 == 1 ~ "Formal",
      b4q12_perv1 == 4 ~ "Semi-Formal",
      b4q12_perv1 %in% c(2, 3, 5) ~ "Informal",
      b4q12_perv1 == 6 ~ "No Training"
    )
  )) %>%
  filter(labour_force == "Yes") %>%
  crosstab_3way(x = b1q3_perv1,z=b4q5_perv1,y = training_type, weight = weight_f,unwt_n = TRUE)
```


```{r}
#b5pt1q9_perv1: principal enterprise type code, 
#b4q5_perv1: Sex,
#b5pt1q9_perv1:Location of Enterprise,
#b1q3_perv1: Sector
per_fv_2020 %>%
  mutate(
    location_work = if_else(is.na(b5pt1q8_perv1) & !nic_3digit_principal %in% c(11,12,13,15) & worker_yn=="Yes",b5pt2q7_perv1,b5pt1q8_perv1))%>%
  filter(working_age_yn == TRUE &
           worker_yn == "Yes") %>%
  crosstab_3way(
    x = b1q3_perv1,
    z=b4q5_perv1,
    y = location_work,
    weight = weight_f,
    unwt_n = TRUE,
    format = "long"
  )
```

