---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(pollster)
```
 

```{r}
per_fv_2023=read_parquet("./data/financial year/plfs_per_fv_2023.parquet")
plfs_2023_hhv1=read_parquet("./data/financial year/plfs_hh_v1_2023.parquet")
```

```{r}
per_fv_2023=per_fv_2023%>%
  mutate(nic_2digit_principal=substr(b5pt1q5_perv1,1,2),
         nic_2digit_subsidiary=substr(b5pt2q5_perv1,1,2),
         nic_3digit_principal=substr(b5pt1q5_perv1,1,3),
         nco_1digit_principal=substr(b5pt1q6_perv1,1,1))%>%
  type.convert(as.is=T)%>%
  mutate(dummy_area="All India",
          age_group=case_when(b4q6_perv1<15~"0-15",
                              b4q6_perv1>=15 & b4q6_perv1<30~"15-29",
                              b4q6_perv1>=30 & b4q6_perv1<50~"30-49",
                              b4q6_perv1>=50 & b4q6_perv1<60~"50-59",
                              b4q6_perv1>=60~"60 and Above"),
         labour_force=if_else(b5pt1q3_perv1<=81 | b5pt1q7_perv1==1,"Yes","No"),
         worker_yn=if_else(b5pt1q3_perv1<81 | b5pt1q7_perv1==1,"Yes","No"),
         weight_f =  if_else(NSS_perv1==NSC_perv1,mult_perv1/400,mult_perv1/800),
         working_age_yn=age_group %in% c("15-29","30-49","50-59"),"Yes","No")
```



```{r}
#Labour force
sum(per_fv_2023 %>%
      filter(
        age_group %in% c("15-29", "30-49", "50-59") &
          labour_force == "Yes"
      ) %>% select(weight_f)) / sum(per_fv_2023 %>%
                                      filter(age_group %in% c("15-29", "30-49", "50-59")) %>% select(weight_f))

#Labour force: Female
sum(per_fv_2023 %>%
      filter(
        age_group %in% c("15-29", "30-49", "50-59") &
          labour_force == "Yes" & 
          b4q5_perv1==2) %>% select(weight_f)) / sum(per_fv_2023 %>%
                                      filter(age_group %in% c("15-29", "30-49", "50-59") & b4q5_perv1==2) %>% select(weight_f))

#Labour force: Rural Female
sum(per_fv_2023 %>%
      filter(
        age_group %in% c("15-29", "30-49", "50-59","60 and Above") &
          labour_force == "Yes" & 
          b4q5_perv1==2 & 
          b1q3_perv1==1) %>% select(weight_f)) / sum(per_fv_2023 %>%
                                      filter(age_group %in% c("15-29", "30-49", "50-59","60 and Above") & b4q5_perv1==2 & b1q3_perv1==1) %>% select(weight_f))

#Labour force: Rural Female (15-29)
sum(per_fv_2023 %>%
      filter(
        age_group %in% c("60 and Above") &
          labour_force == "Yes" & 
          b4q5_perv1==2 & 
          b1q3_perv1==2) %>% select(weight_f)) / sum(per_fv_2023 %>%
                                      filter(age_group %in% c("60 and Above") & b4q5_perv1==2 & b1q3_perv1==2
                                             ) %>% select(weight_f))

#Labour force: Rural Female (15-49)
sum(per_fv_2023 %>%
      filter(
        b4q6_perv1>=49 & b4q6_perv1<59 &
          labour_force == "Yes" & 
          b4q5_perv1==2 & 
          b1q3_perv1==2) %>% select(weight_f)) / sum(per_fv_2023 %>%
                                      filter( b4q6_perv1>=49 & b4q6_perv1<59 & b4q5_perv1==2 & b1q3_perv1==2) %>% select(weight_f))
#Labour force: Rural Male (15-49)
sum(per_fv_2023 %>%
      filter(
        b4q6_perv1>=18 & b4q6_perv1<=25 &
          labour_force == "Yes" & 
          b4q5_perv1==1 & 
          b1q3_perv1==1) %>% select(weight_f)) / sum(per_fv_2023 %>%
                                      filter( b4q6_perv1>=18 & b4q6_perv1<=25 & b4q5_perv1==1 & b1q3_perv1==1) %>% select(weight_f))
```


```{r}
#b5pt1q9_perv1: principal enterprise type code, 
#b4q5_perv1: Sex,
#b5pt1q9_perv1:Location of Enterprise,
#b1q3_perv1: Sector
per_fv_2023 %>%
  mutate(
    location_work = if_else(is.na(b5pt1q8_perv1) & !nic_3digit_principal %in% c(11,12,13,15) & worker_yn=="Yes",b5pt2q7_perv1,b5pt1q8_perv1))%>%
  filter(working_age_yn == TRUE &
           worker_yn == "Yes") %>%
  crosstab(
    x = dummy_area,
    #z= b4q5_perv1,
    y = location_work,
    weight = weight_f,
    unwt_n = TRUE,
    format = "long"
  )
```

```{r}
per_fv_2023 %>%
  mutate(enterprise_type=if_else(worker_yn=="Yes" & is.na(b5pt1q9_perv1),b5pt2q8_perv1,b5pt1q9_perv1))%>%
  filter(working_age_yn == TRUE &
           worker_yn == "Yes") %>%
  crosstab_3way(
    z = b4q5_perv1,
    x=b1q3_perv1,
    y = b5pt1q3_perv1,
    weight = weight_f,
    unwt_n = TRUE,
    format = "long"
  )
```


```{r}

per_fv_2023%>%
  mutate(nic_code_usual=case_when(working_age_yn == TRUE &
           worker_yn == "Yes" & is.na(nic_2digit_principal)~nic_2digit_subsidiary,
           b4q6_perv1>=15 & b4q6_perv1<30 &
           worker_yn == "Yes" & !is.na(nic_2digit_principal)~nic_2digit_principal,
           worker_yn=="No"~NA))%>%
 filter(working_age_yn == TRUE &
          age_group %in% c("15-29","30-49","50-59","60 and Above"))%>%
  crosstab(
    x=dummy_area,
    y = nic_code_usual,
    weight = weight_f,
    unwt_n = TRUE,
    format="long"
  )
```

```{r}
per_fv_2023%>%
  merge(plfs_2023_hhv1%>% #Merge for Caste
          type.convert(as.is=T)%>%
          select(3,13:16,24),
        by.x = c("qtr_perv1","b1q1_perv1","b1q13_perv1","b1q14_perv1","b1q15_perv1"),
        by.y =c("qtr_hhv1","b1q1_hhv1","b1q13_hhv1","b1q14_hhv1","b1q15_hhv1"),
        all.x = TRUE)%>%
  crosstab(x=state_perv1,y=b3q4_hhv1,weight = weight_f,unwt_n = TRUE)#caste
```

This does not contains the employment code 21: working in household enterprise
```{r}
per_fv_2023%>%
  merge(plfs_2023_hhv1%>% #Merge for Caste
          type.convert(as.is=T)%>%
          select(3,13:16,24),
        by.x = c("qtr_perv1","b1q1_perv1","b1q13_perv1","b1q14_perv1","b1q15_perv1"),
        by.y =c("qtr_hhv1","b1q1_hhv1","b1q13_hhv1","b1q14_hhv1","b1q15_hhv1"),
        all.x = TRUE)%>%
  filter(working_age_yn==TRUE & b6q5_perv1 <91 & b1q3_perv1==1 & total_wages > 0) %>%
mutate(total_earnings=b6q9_perv1+b6q10_perv1,
      quantil_n=ntile(total_wages,n = 5),
      all_india="Yes",
      employment_status= case_when(b6q5_perv1 %in% c(11,12,21,61,62)~"self employed",
                                   b6q5_perv1 %in% c(31,71,72,81,82)~"Salaried",
                                   b6q5_perv1 %in% c(41,42,51)~"Casual Labour"))%>% filter(employment_status=="Casual Labour")%>%
  #crosstab(x = all_india,y =b3q4_hhv1,weight = weight_f,unwt_n = TRUE)
  group_by(quantil_n,b3q4_hhv1)%>%
  summarise(mean_wage=weighted.mean(total_wages,w = weight_f,na.rm=TRUE))%>%
  spread(key = b3q4_hhv1, value = mean_wage)
  
```

```{r}
per_fv_2023$total_wages=apply(per_fv_2023 %>% select(64,68,74,78,84,88,94,98,104,108,114,118,124,128), 1, function(row) sum(row[row >= 0 & !is.na(row)], is.na(row)))


per_fv_2023%>%
  merge(plfs_2023_hhv1%>% #Merge for Caste
          type.convert(as.is=T)%>%
          select(3,13:16,24),
        by.x = c("qtr_perv1","b1q1_perv1","b1q13_perv1","b1q14_perv1","b1q15_perv1"),
        by.y =c("qtr_hhv1","b1q1_hhv1","b1q13_hhv1","b1q14_hhv1","b1q15_hhv1"),
        all.x = TRUE)%>%
  mutate(total_earnings=if)
  filter(working_age_yn==TRUE & b6q5_perv1 <91 & b1q3_perv1==1)%>%
  group_by(b6q5_perv1)%>% summarise(avg_earnings=)
```

```{r}
#Type of training

per_fv_2020 %>%
  mutate(training_type = as.factor(
    case_when(
      b4q12_perv1 == 1 ~ "Formal",
      b4q12_perv1 == 4 ~ "Semi-Formal",
      b4q12_perv1 %in% c(2, 3, 5) ~ "Informal",
      b4q12_perv1 == 6 ~ "No Training")),
     employment_status= as.factor(case_when(b6q5_perv1 %in% c(11,12,21,61,62)~"self employed",
                                   b6q5_perv1 %in% c(31,71,72,81,82)~"Salaried",
                                   b6q5_perv1 %in% c(41,42,51)~"Casual Labour"))) %>%
  filter(labour_force == "Yes") %>%
  crosstab(x = training_type, y = employment_status, weight = weight_f,unwt_n = TRUE)
```

```{r}

```

