---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(pollster)
library(arrow)
```


```{r}
plfs_2023_hhv1=read_dta("/datacalendar_year/2023/plfs_2023_hhv1.parquet")
plfs_2023_perv1=read_dta("data/calendar_year/2023/plfs_2023_perv1.parquet")
```

```{r}
per_fv_2022 %>%
  mutate(training_type = as.factor(
    case_when(
      b4q12_perv1 == 1 ~ "Formal",
      b4q12_perv1 == 4 ~ "Semi-Formal",
      b4q12_perv1 %in% c(2, 3, 5) ~ "Informal",
      b4q12_perv1 == 6 ~ "No Training"
    )
  )) %>%
  filter(labour_force == "Yes") %>%
  crosstab(x = dummy_area,y = training_type, weight = weight_f,unwt_n = TRUE)
```



```{r}
plfs_2023_perv1%>%
   type.convert(as.is=T)%>%
   mutate(dummy_area="All India",
          age_group=case_when(b4q6_perv1<15~"0-15",
                              b4q6_perv1>=15 & b4q6_perv1<60~"15-59",
                              b4q6_perv1>=60~"60 and Above"),
          weight_f =  if_else(nss_cperv1==nsc_cperv1,mult_cperv1/400,mult_cperv1/800),
          general_education=case_when(b4q9_cperv1!=1~"Technical Education",
                                      b4q9_cperv1==1 & b4q8_cperv1 %in% c(1,2,3)~"No General Education",
                                      b4q9_cperv1==1 & b4q8_cperv1 %in% c(5,6,7,8,10)~"Attended School",
                                      b4q9_cperv1==1 & b4q8_cperv1 %in% c(11,12,13)~"Attended College"))%>%
    filter(age_group %in% c("15-59"))%>% # Age filter
  crosstab(x=b4q5_cperv1,y=general_education,weight = weight_f,unwt_n = TRUE)
```


```{r}
plfs_2023_perv1%>%
   type.convert(as.is=T)%>%
   mutate(dummy_area="All India",
          age_group=case_when(b4q6_perv1<15~"0-15",
                              b4q6_perv1>=15 & b4q6_perv1<60~"15-59",
                              b4q6_perv1>=60~"60 and Above"),
          weight_f =  if_else(nss_cperv1==nsc_cperv1,mult_cperv1/400,mult_cperv1/800),
          general_education=case_when(b4q9_cperv1!=1~"Technical Education",
                                      b4q9_cperv1==1 & b4q8_cperv1 %in% c(1,2,3)~"No General Education",
                                      b4q9_cperv1==1 & b4q8_cperv1 %in% c(5,6,7,8,10)~"Attended School",
                                      b4q9_cperv1==1 & b4q8_cperv1 %in% c(11,12,13)~"Attended College"))%>%
    filter(age_group %in% c("15-59"))%>% # Age filter
  crosstab(x=b1q3_cperv1,y=b4q12_cperv1,weight = weight_f,unwt_n = TRUE)
```

```{r}
per_fv_2023%>%
  type.convert(as.is=T)%>%
  filter(labour_force=="Yes")%>% #Age filter
  merge(plfs_2023_hhv1%>% #Merge for Caste
          type.convert(as.is=T)%>%
          select(3,13:16,24),
        by.x = c("qtr_perv1","b1q1_perv1","b1q13_perv1","b1q14_perv1","b1q15_perv1"),
        by.y =c("qtr_hhv1","b1q1_hhv1","b1q13_hhv1","b1q14_hhv1","b1q15_hhv1"),
        all.x = TRUE)%>%
  mutate(dummy_area="All India",#Dummy variable for all india
         weight_f =  if_else(NSS_perv1==NSC_perv1,mult_perv1/400,mult_perv1/800))%>%
  crosstab(x=b1q3_perv1,y=b4q12_perv1,weight = weight_f,unwt_n = TRUE)#caste
```


```{r}
#x=Rural/urban, y=Type of training
plfs_2023_perv1 %>%filter(b4q6_perv1>14 & b4q6_perv1<60)%>%
  type.convert(as.is=T)%>%
  mutate(dummy_area="All India",
         weight_f =  if_else(nss_cperv1==nsc_cperv1,mult_cperv1/400,mult_cperv1/800))%>%
  crosstab(x=b1q3_cperv1,y=b4q12_cperv1,weight = weight_f,unwt_n = TRUE)
```

```{r}
#General Education
per_fv_2022%>%
   type.convert(as.is=T)%>%
   mutate(dummy_area="All India",
          age_group=case_when(b4q6_perv1<15~"0-15",
                              b4q6_perv1>=15 & b4q6_perv1<60~"15-59",
                              b4q6_perv1>=60~"60 and Above"),
          weight_f =  if_else(NSS_perv1==NSC_perv1,mult_perv1/400,mult_perv1/800),
          general_education=case_when(b4q9_perv1!=1~"Technical Education",
                                      b4q9_perv1==1 & b4q8_perv1 %in% c(1,2,3)~"No General Education",
                                      b4q9_perv1==1 & b4q8_perv1 %in% c(5,6,7,8,10)~"Attended School",
                                      b4q9_perv1==1 & b4q8_perv1 %in% c(11,12,13)~"Attended College"))%>%
    filter(age_group %in% c("15-59"))%>% # Age filter
  crosstab(x=b4q5_perv1,y=general_education,weight = weight_f,unwt_n = TRUE)

per_fv_2022%>%
   type.convert(as.is=T)%>%
   mutate(dummy_area="All India",
          age_group=case_when(b4q6_perv1<15~"0-15",
                              b4q6_perv1>=15 & b4q6_perv1<60~"15-59",
                              b4q6_perv1>=60~"60 and Above"),
          weight_f =  if_else(NSS_perv1==NSC_perv1,mult_perv1/400,mult_perv1/800),
          general_education=case_when(b4q9_perv1!=1~"Technical Education",
                                      b4q9_perv1==1 & b4q8_perv1 %in% c(1,2,3)~"No General Education",
                                      b4q9_perv1==1 & b4q8_perv1 %in% c(5,6,7,8,10)~"Attended School",
                                      b4q9_perv1==1 & b4q8_perv1 %in% c(11,12,13)~"Attended College"))%>%
    filter(age_group %in% c("15-59"))%>% # Age and working Status filter
   filter(b1q3_perv1==1)%>%
  #crosstab(x=b1q3_perv1,y=general_education,weight = weight_f,unwt_n = TRUE)
  crosstab_3way(x=b4q5_perv1,z=general_education,y=b4q12_perv1,weight = weight_f,unwt_n = TRUE)
  #crosstab_3way(x=b1q3_perv1,z=b4q5_perv1,y=general_education,weight = weight_f,unwt_n = TRUE)
```

